### PR TITLE
Set lower bound on docker version

### PR DESCRIPTION
**Pull request by naomielst**
From my experience, the docker version must be >= 4.0.0

### CODE REVIEW

**Review by thedrow — APPROVED** [review]

**Comment by tillahoffmann** [comment]
This will also need a rebuild of the requirements (cf. #188). The motivation behind completely pinning down the requirements for tests is to be able to separate "issues caused by dependency versions changing" from "issues introduced in a PR".

**Comment by tillahoffmann** [comment]
> I suggest using something like poetry instead and caching the lock file.

Yup, those requirements are locked down dependencies. We just generate them using [pip-tools](https://github.com/jazzband/pip-tools) rather than poetry or pipenv.

**Comment by thedrow** [comment]
@tillahoffmann Would you mind doing it this time?

**Comment by tillahoffmann** [comment]
See #203.

**Pull request closed without merging**
