### PR TITLE
fix(kafka): wait_for_logs in kafka container to reduce lib requirement

### LINKED ISSUE #351: Make the kafka package dependency optional to be able to use confluent_kafka
**Describe the bug**

We use confluent_kafka in the project and it's strange that we need another kafka sdk (kafka-python) just to check that the container is running.

**To Reproduce**

Install testcontainers-kafka -> observe that a kafka-python gets installed

### PR DESCRIPTION
**Pull request by gudjonragnar**
Use `wait_for_logs` to wait for startup instead of waiting for successful connection via kafka-python. Also removes the dependency on kafka-python.

Closes #351

### CODE REVIEW

**Comment by jankatins** [comment]
LGTM, we would really like to see this because we use confluent kafka in the project...

**Comment by gudjonragnar** [comment]
I will try to find some time beginning of next week 👍

**Comment by gudjonragnar** [comment]
Should be up to date now, unless I missed somethink with the big changes done to the repo

**Review by jankatins — APPROVED** [review]
LGTM (not a maintainer)

**Comment by alexanderankin** [comment]
https://github.com/gudjonragnar/testcontainers-python/pull/1

**Comment by alexanderankin** [comment]
Reminder to myself to get this merged #446

**Pull request merged**
