### PR TITLE
Add gitlab ci.

### PR DESCRIPTION
**Pull request by tillahoffmann**
There appear to be a number of issues with running tests on gitlab, e.g. #68, #60, #43, #25. Hopefully running tests on gitlab as part of the build will help us catch those issues.

Unfortunately, because of https://gitlab.com/gitlab-org/gitlab/issues/5667, we cannot run gitlab builds on pull requests from forks.

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
Why not use Github's actions?

**Comment by tillahoffmann** [comment]
@SergeyPirogov, updated above with rationale.

**Comment by SergeyPirogov** [comment]
@tillahoffmann I see, good. So then it's better to provide a link to GitLab CI in the readme

**Comment by tillahoffmann** [comment]
Yes, good idea. Will add a link to the readme, but will try to get it to build first. 🙂

**Comment by tillahoffmann** [comment]
Available at https://github.com/testcontainers/testcontainers-python/blob/gitlab2/.gitlab-ci.yml if required, but [gitlab doesn't support fork builds](https://gitlab.com/gitlab-org/gitlab/-/issues/5667) which makes it problematic for open source use.

**Pull request closed without merging**
