### PR TITLE
Bug/missing cryptography mysql

### PR DESCRIPTION
**Pull request by vindex10**
When installed into a clean environment, testcontainers-mysql requires `cryptography` package to authenticate with "mock db". This pull requests specifies the requirement for `pymysql` (which is the reason why cryptography is required):

https://github.com/PyMySQL/PyMySQL/blob/b1399c95bcde8ef73cbc3a6d4e8bf767094bbd9e/pyproject.toml#L31

This happens only for mysql:8, mysql:5 doesn't have this issue.

### CODE REVIEW

**Comment by pffijt** [comment]
@vindex10 Thank you for submitting your contribution!

**Comment by vindex10** [comment]
Thank you! It seems tests for mysql passed :)

**Comment by pffijt** [comment]
@vindex10 Indeed the mysql tests are succeeding. I will have look at the other failing tests

**Comment by tillahoffmann** [comment]
Thanks for having a look into the other failing tests. Could you also rebuild the requirements files by running `make requirements` from the root directory?

**Comment by vindex10** [comment]
didnt work out of the box

```
  ERROR: Could not find a version that satisfies the requirement codecov>=2.1.0 (from versions: none)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('codecov>=2.1.0')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 350, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('codecov>=2.1.0'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/piptools/scripts/compile.py", line 592, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 595, in resolve
    compatible_existing_constraints=compatible_existing_constraints,
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 628, in _do_resolve
    check_supported_wheels=not self.options.target_dir,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for codecov>=2.1.0
make: *** [Makefile:70: requirements/3.7.txt] Error 1
```

**Comment by vindex10** [comment]
local build failed. @tillahoffmann please allow workflows :) I rebased on top of #331

**Comment by vindex10** [comment]
@tillahoffmann Hi! I managed to run `make requirements` now and pushed the new version. could you please trigger the tests?

**Comment by vindex10** [comment]
@tillahoffmann  all checks have passed! :tada:

**Comment by vindex10** [comment]
@tillahoffmann please allow the workflows again, I resolved the conflicts.

I will update the requirements with `get_requirements.py` if the tests fail

**Comment by vindex10** [comment]
@tillahoffmann all checks have passed! should we merge before it gained more conflicts? :)

**Comment by tillahoffmann** [comment]
Thanks @vindex10! Could you please update the requirement files as outlined [here](https://github.com/testcontainers/testcontainers-python/blob/main/.github/PULL_REQUEST_TEMPLATE/new_container.md)?

**Comment by vindex10** [comment]
@tillahoffmann done.
I only did the last step: "python3 get_requirements.py --pr=[]"

I hope it is correct :)

**Comment by vindex10** [comment]
Why were  the 12 checks cancelled? is it expected?

**Comment by vindex10** [comment]
@tillahoffmann could you please comment? I see only successful or cancelled checks, no failed.

**Pull request merged**
