### PR TITLE
Release new version of testcontainers-gcp

### PR DESCRIPTION
**Pull request by barendatnicolab**
For contest, see https://github.com/testcontainers/testcontainers-python/issues/403

Current version on PyPI (0.0.1rc1) is not in sync with branch `main`. This PR will bump the version and as such that version will hold the changes from this commit: https://github.com/testcontainers/testcontainers-python/commit/934c8d884ff513d3ede3b7faab2860f110799585

Not sure what we need to do to actually _publish_ this to PyPI?

### CODE REVIEW

**Comment by markConklin** [comment]
Gently Bumping this. Thank you.

**Comment by alexanderankin** [comment]
I think this depends on Till or Sergei responding with regard to #405 - as currently no other folks have the ability to publish to pypi for this project

**Comment by barendatnicolab** [comment]
Thanks for (trying) to revamp the release cycle @alexanderankin. If there's anything I can do, let me know. For now I've temporarily solved this by publishing a fix to our internal PYPI, but would still love to see it fixed.

**Comment by alexanderankin** [comment]
thanks @barendatnicolab

i've [published a new version 4.0.0-rc2](https://pypi.org/project/testcontainers/#history), which theoretically contains the code which should be published to fix this ticket. I'm still fixing the doctests and various other build stuff, progress on [poetry-refactor](https://github.com/totallyzen/testcontainers-python/tree/poetry-refactor) (issue 408) and later, [poetry-refactor-changes-to-publish](https://github.com/alexanderankin/testcontainers-python/commits/poetry-refactor-changes-to-publish/) branches respectively. I guess either testing this rc version or helping with the doctests both helps?

**Comment by totallyzen** [comment]
hey, please follow #418 for more info

**Pull request closed without merging**
