### PR TITLE
docs: Added badges to README.md

### PR DESCRIPTION
**Pull request by max-pfeiffer**
I added the following badges:
- Poetry
- Ruff
- Supported Python versions
- Workflow runs

### CODE REVIEW

**Comment by alexanderankin** [comment]
here are the ones on readthedocs (which still needs to be fixed on the build side (either transferring the testcontainers-python subdomain, or the testcontainers subdomain set up via someone's auth who has permissions to create webhooks on this repo):

https://github.com/testcontainers/testcontainers-python/blob/d5b855323be06f8d1395dd480a347f0efef75703/index.rst?plain=1#L1-L11

**Comment by alexanderankin** [comment]
maybe it makes sense for the badges to match, maybe not, idk

**Comment by max-pfeiffer** [comment]
@alexanderankin Thanks for pointing that out. I just added the missing badges for docs and codespace. I choose to add the code space badge below the others is this one is breaking the layout a bit. That way it doesn't look too awkward. 

@totallyzen The badges do match now. I just added some additional badges.

**Comment by alexanderankin** [comment]
sorry, i thought this was merging into main, my apologies.

**Pull request merged**
