### PR TITLE
feat(new): add a new Docker Registry test container

### PR DESCRIPTION
**Pull request by max-pfeiffer**
I added a new test container for spinning up a [Docker registry](https://hub.docker.com/_/registry).

### CODE REVIEW

**Comment by totallyzen** [comment]
Hi @max-pfeiffer I'm grooming the ongoing issues for the project (we're rebooting the maintenance, see #405) and I'd like to know more about your test case!

It's nice to have many flavours of containers, but it also means exponentially increasing complexity and cost of running the tests for this project! Therefore we're trying to stick to the most commonly used containers for now.

**Comment by alexanderankin** [comment]
Since 2024 I think the case may (!) actually be stronger than ever to support it(??)

**Comment by max-pfeiffer** [comment]
Hi @totallyzen, when building Docker containers with Docker Buildx there is currently no option to test your containers locally without a local registry. Otherwise Buildx pushes your image to Docker Hub, which is not what you want in a test case. More and more you need to use Buildx for effienciently building images and especially multi arch images.

When you use Docker Python libraries like [docker-py](https://github.com/docker/docker-py) or [python-on-whales](https://github.com/gabrieldemarmiesse/python-on-whales)  to build and test Docker images, what a lot of persons and DevOps engineers like me nowadays do, a test container comes in very handy.

BTW: I use the testcontainers package quite a bit and have time to spare. If you still need a helping hand I would be happy to jump in.

**Comment by totallyzen** [comment]
@max-pfeiffer thanks, exactly what I meant to express! :smile: Not to push back, but to explain why this is useful (and put it in the readme of the module) :pray: 

@alexanderankin indeed, I meant more the "average developer" use case rather than the specialised use case of the Docker company testing/building their own software! :) If it's only the latter, there would have been arguments that they have been successful without AND they develop their software in Go these days.


Having said that, 

Max you're very welcome to join! You can start by rebasing your own PR to match the new project structure:
- put your source-code in `modules/*` - basically copy/paste
- you put your package in `pyproject.toml` in [here](https://github.com/testcontainers/testcontainers-python/blob/main/pyproject.toml#L29-L52)
- you need to declare an extra even if you don't have any current deps (for future-proofing and making CI code simpler to write) [like nginx for example](https://github.com/testcontainers/testcontainers-python/blob/main/pyproject.toml#L102)
- instead of `main.yml` you put your module in `ci-community.yml`

After that happy to review your PR and see what you'd like to work on next! :pray:

**Comment by max-pfeiffer** [comment]
@totallyzen Thanks for the info. I will work on it this weekend.

BTW: I just stumbled across that page: https://github.com/testcontainers/testcontainers-python/contribute
It seemed to be outdated as you guys just refactor the project.

**Comment by totallyzen** [comment]
> It seemed to be outdated as you guys just refactor the project.

Yes, very much, sorry about that. We're both operating on spare time and energy.
Fixes to the docs are highly appreciated! :heart:

**Comment by max-pfeiffer** [comment]
@totallyzen I just rebased my PR with main branch and did the refactoring to match the new project setup. 

I struggle to understand what I need to do in `ci-community.yml`. Looking at that workflow there seems to be nothing to add for me as module changes are tracked automatically.

**Comment by totallyzen** [comment]
hey @max-pfeiffer indeed, `ci-community.yml` is auto-tracking modules as long as you add them in the `pyproject.toml`, which you did!

I ran the checks for you, seems like some docs and linting errors were made.
I think you should be able to see the output and fix them!
I can also highly recommend installing `pre-commit` and running it so you get early feedback! :) 

Other than that, you're almost done here! Thanks for the effort!

**Comment by max-pfeiffer** [comment]
Hi @totallyzen , hmm I saw that that pre-commit config in project root, but pyproject.toml was missing the pre-commit depencencies (pre-commit, black, ruff). So I would say the pre-commit setup is not really there and ready to use for software engineers. :smiley:

I quickly fixed that in this PR: https://github.com/testcontainers/testcontainers-python/pull/438
Is this something you think we could merge in for completing this PR?

**Pull request merged**
