### PR TITLE
fix: added types to exec & tc_properties_get_tc_host

### PR DESCRIPTION
**Pull request by Dandiggas**
https://github.com/testcontainers/testcontainers-python/issues/557 -  trying to solve this issue by adding types.

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
this LGTM overall, thanks @Dandiggas!

**Comment by errordeveloper** [comment]
@kiview could you please approve the workflows to run?

**Comment by alexanderankin** [comment]
We'll take a look

**Comment by alexanderankin** [comment]
yep so we support python 3.9 for now so cant use the pipe syntax for `typing.Union` - but the other type is indeed wrong so we could merge a pr that just fixes a single type, would probably prefer a PR that fixes types more comprehensively like #504 - if you want to provide feedback on that branch, that could help it along - it was only not merged because i was not confident in 100% of the choices made in there at the time.

ill leave this open in case you want to replace with `from typing import Union`

**Comment by Dandiggas** [comment]
@alexanderankin Now supports python 3.9, please review when possible

**Comment by alexanderankin** [comment]
thank you for the contribution! if you are interested in improving typing in this library are other types that I have started but did not feel confident enough to merge #504

**Pull request merged**
