### PR TITLE
Fix typo in method name 'get_wrapped_contaner'

### PR DESCRIPTION
**Pull request by dpursehouse**

### CODE REVIEW

**Comment by dpursehouse** [comment]
@SergeyPirogov any chance to merge this?  I don't think the failing checks are caused by this.

**Comment by SergeyPirogov** [comment]
@dpursehouse Who knows ;) Need to try to make tests pass and the merge to be confident

**Comment by dpursehouse** [comment]
Reopen to trigger CI again.

**Comment by dpursehouse** [comment]
Done in #79

**Pull request closed without merging**
