### PR TITLE
chore(deps): bump docker from 7.0.0 to 7.1.0

### PR DESCRIPTION
**Pull request by tarilabs**
Hi 👋 
my attempt at #577 since that is affecting our project as well, cannot replicate testing on my machine (regardless of this upgrade) so trusting in GHA while raising this PR, hope this helps?

### CODE REVIEW

**Review by alexanderankin — CHANGES_REQUESTED** [review]
wait, what? our CI never broke - we need someone who is facing the issue to test. Otherwise this involves figuring out where we use `http+docker` - is that used over unix sockets? is that only on windows? @NikiforovG would know - he faced the issue, so would @ErwinJapie , or presumably any of the other folks who liked the comments on #577.

lastly, this doesn't make sense to bump docker without setting requests version to one of the problematic ones, which i believe by now are yanked - https://pypi.org/project/requests/#history - perhaps 2.32.2 is still broken, I have not checked myself

**Comment by tarilabs** [comment]
> wait, what? our CI never broke

not what I said, and sorry if I was not able to express myself fully.
On my machine, checking out main and `poetry run pytest core/` fails on main, but that might be due to my system configuration.

Hence I raised the PR to trust on the GHA CI.

**Comment by tarilabs** [comment]
> lastly, this doesn't make sense to bump docker without setting requests version to one of the problematic ones, which i believe by now are yanked - https://pypi.org/project/requests/#history - perhaps 2.32.2 is still broken, I have not checked myself

sorry I missed this, I made the assumption `docker` enforced this ^version, and after your comment I realize it's not.

**Comment by tarilabs** [comment]
Shall I enforce `requests` to `^2.32.2` in pyproject.toml ?

**Comment by kiview** [comment]
@tarilabs From my understanding, since the new version of docker-py is already released, it should be fixed for users of our testcontainers-python as well when installing dependencies.

**Comment by tarilabs** [comment]
> @tarilabs From my understanding, since the new version of docker-py is already released, it should be fixed for users of our testcontainers-python as well when installing dependencies.

ack, I thought i'd use this to bump the lock file for this project benefit too,

https://github.com/testcontainers/testcontainers-python/blob/78b6f0ecb15e8cba687eb4588c5ce19ca32208bc/poetry.lock#L903-L904

and

https://github.com/testcontainers/testcontainers-python/blob/78b6f0ecb15e8cba687eb4588c5ce19ca32208bc/poetry.lock#L3393-L3394

as I thought is the same kind of issue, but I might have missed something.

thanks anyway :)

**Comment by tarilabs** [comment]
> No worries, I originally thought the same, until I was further educated on the idiosyncrasies of the Python ecosystem (I'm mostly a Java dev). Thanks for helping out 🙌

can you share some educational sources you are referring to @kiview here, please?
I'm mostly from Java background too 😅  so I could make the use of it too :)

**Comment by alexanderankin** [comment]
can you share about how it is broken on your machine, ideally your machine exhibits same behavior as this repo's ci, which as above, does not break due to this `http+docker` issue

**Pull request closed without merging**
