### PR TITLE
added Neo4j container

### PR DESCRIPTION
**Pull request by eastlondoner**
Let me know if you'd like anything else for this.

### CODE REVIEW

**Comment by eastlondoner** [comment]
I've implemented my own equivalent of  `wait_for_logs` but can switch to use the one from https://github.com/testcontainers/testcontainers-python/pull/55 when available

**Comment by tillahoffmann** [comment]
@eastlondoner, #55 has now been merged if you want to use that version of `wait_for_logs`.

**Comment by eastlondoner** [comment]
@tillahoffmann thanks, I've updated the PR :-)

**Comment by eastlondoner** [comment]
@tillahoffmann I've rebased, updated the code and added basic docs.

I re-built the requirements files which pulled in a load of updated dependencies, I hope that's OK.

**Comment by eastlondoner** [comment]
@tillahoffmann so that requirements update makes the docker client too new for the CI server. So I'll pin `docker-compose` for now ... new commit incoming.

**Comment by tillahoffmann** [comment]
Yes, it looks a bit fiddly. It looks like it might be `docker` rather than `docker-compose`. Fancy adding the pinned version to `requirements.in` rather than `setup.py` (that'll mean people can still install a newer version on their machine if they want)?

**Comment by eastlondoner** [comment]
OK. I manually pinned the docker version in `requirements.in` Looks like CI is working now :-)

**Comment by tillahoffmann** [comment]
Great! I'll try to send you a PR to the PR to make sure we don't have the same problem in the future. Shouldn't be long.

**Comment by tillahoffmann** [comment]
https://github.com/eastlondoner/testcontainers-python/pull/1

**Pull request merged**
