### PR TITLE
Add docker compose module with V2 support

### PR DESCRIPTION
**Pull request by carlosemart**
Co-authored-by: @jhnnsrs and @psschwei

Fixes https://github.com/testcontainers/testcontainers-python/issues/306

I recover the compose module and the work do it on https://github.com/testcontainers/testcontainers-python/pull/362, fixing a bug in the loading of the docker-compose files that caused the tests to never finish.

I have also removed the dependency of the docker-compose module, delegating the calls to the client installed in the system.

### CODE REVIEW

**Comment by alexanderankin** [comment]
linking also #358

**Review by alexanderankin — APPROVED** [review]
if i approve this, do tests run?

**Comment by carlosemart** [comment]
@alexanderankin, I don't know who should approve the pr, but there should be an "Approve and run" button like this one: 
imagen

**Comment by carlosemart** [comment]
I rebase main branch with poetry changes

**Comment by totallyzen** [comment]
hey @carlosemart sorry for the disappiontment, we've decided to rewrite the compose from the ground up, because it isn't just a matter of `subprocess.run(["docker", "compose"])` but fixing the underlying mechanism with fetching ports. `docker compose ps --format json` is a thing now so decided to make it much more strongly typed. 

see #426

of course, your review is welcome on the PR, however I would like to avoid duplicating the effort on multiple PRs.
We're also collating a bunch of fixes for `compose` onto that PR!

**Comment by carlosemart** [comment]
Duplicate with https://github.com/testcontainers/testcontainers-python/pull/426

**Pull request closed without merging**
