### PR TITLE
Added documentation to DockerContainer

### PR DESCRIPTION
**Pull request by barjb**
Added DockerContainer documentation. Documented modules from testcontainers/core package are contained in readme including: container, docker_container and waiting_utils. #282

Changes made:
- added intersphinx for docker-py referencing
- documented DockerContainer
- changed testcontainers/core README.rst
- corrected return type in wait_for_logs

### CODE REVIEW

**Comment by gaby** [comment]
@tillahoffmann Any chance of merging this? I wasted an hour reading source code because this repo is not documented correctly

**Comment by tillahoffmann** [comment]
Yes, definitely. The tests aren't passing at the moment, unfortunately.

**Comment by gaby** [comment]
@barjb Can you take a look at some of the errors in the CI. Your PR is really helpfull 😁

**Comment by barjb** [comment]
@gaby @tillahoffmann Thanks for the positive feedback. I did not run doctest before last pull request, and now it passes on my local machine.

**Comment by gaby** [comment]
@tillahoffmann Friendly ping, we need these docs

**Pull request closed without merging**
