### PR TITLE
Add support for Keycloak

### PR DESCRIPTION
**Pull request by timbmg**
Keycloak is an open source identity and access management solution.

Reference: https://hub.docker.com/r/jboss/keycloak/

### CODE REVIEW

**Comment by yakimka** [comment]
Please add documentation to this PR

**Comment by timbmg** [comment]
What documentation would be helpful @yakimka?

**Review by tillahoffmann — APPROVED** [review]
Looks great, just needs a rebase on `master`.

**Comment by timbmg** [comment]
> Looks great, just needs a rebase on `master`, and the `keycloack` line should be added to the `test-components` matrix in `.github/workflows/main.yml`.

done ✅ @tillahoffmann

**Comment by tillahoffmann** [comment]
Looks like one more step is required: `make requirements/3.10.txt` now that we're also testing against 3.10. Apologies for the piecemeal feedback.

**Comment by tillahoffmann** [comment]
Thanks for the contribution!

**Pull request merged**
