### PR TITLE
Add new postgresql env vars (#1)

### PR DESCRIPTION
**Pull request by ksquaredkey**
* Add support for additional PostgreSQL Container env variables.

Added interface for environment variables that the PostgreSQL container now supports:

* POSTGRES_INITDB_ARGS
* POSTGRES_INITDB_WALDIR
* POSTGRES_HOST_AUTH_METHOD
* PGDATA

As a bonus, added tests for POSTGRES_INITDB_ARGS and POSTGRES_HOST_AUTH_METHOD.

Issue #278

### CODE REVIEW

**Comment by ksquaredkey** [comment]
Hmm, is testcontaners-python an abandoned project?

**Comment by tillahoffmann** [comment]
Hey, sorry for the delay. I'll revisit this PR once #296 is merged.

**Comment by ksquaredkey** [comment]
Uh.  Not sure why the PR above changed.  I renamed master to main in my Fork to match the upstream here about the time this says I deleted the master branch.  From the look of #296, it looks like I'll have substantial refactoring to make to match current main, so maybe not a bad thing if I start with a fresh post-296 PR.

**Comment by ksquaredkey** [comment]
If anyone stumbles across this old PR, I never got around to refactoring it and @santi posted a better, cleaner way to do what I wanted in the comments of #278.

**Pull request closed without merging**
