### PR TITLE
Add container for RabbitMQ

### PR DESCRIPTION
**Pull request by vryazanov**
@tillahoffmann pls have a look

### CODE REVIEW

**Comment by vryazanov** [comment]
@SergeyPirogov pls review

**Comment by SergeyPirogov** [comment]
@vryazanov There are flake 8 violations

**Comment by KerstenBreuer** [comment]
Hi @vryazanov, so sorry, I didn't saw your PR and have now my own open (#162).
Could we integrate our solutions? Maybe I could do a PR to your fork?

**Comment by vryazanov** [comment]
> Hi @vryazanov, so sorry, I didn't saw your PR and have now my own open (#162). Could we integrate our solutions? Maybe I could do a PR to your fork?

oops, I completely forgot about this pr. your pr looks a way better to me than mine :), so I'll close this one.

**Pull request closed without merging**
