### PR TITLE
Update compose to work with both "docker-compose" as well as "docker compose" 

### LINKED ISSUE #306: Allow configuring the `docker-compose` executable path
**Describe the bug**

On newer docker setups, docker-compose is part of docker under a docker sub commands: `docker compose`

This makes this library fail to find `docker-compose` when needed.

For now I have a little script but I expect this library to be able to change the executable name:
```sh
#!/usr/bin/env bash

exec docker compose "$@"
```

### PR DESCRIPTION
**Pull request by jhnnsrs**
Fixes #306

Sorry for the deletion of the old pull-request.

### CODE REVIEW

**Review by ash1425 — APPROVED** [review]
LGTM

**Comment by bercikr** [comment]
what do we need to do to get this approved, can I reopen the pull request. We are hitting an issue related to this...

**Comment by tillahoffmann** [comment]
We need a rebase on `main` to get this merged.

**Comment by tillahoffmann** [comment]
Closing in favor of #362.

**Pull request closed without merging**
